### ISSUE TITLE
OIDC frontend db_uri not optional

### ISSUE THREAD

**Issue by lhoekenga** [SUNET/SATOSA#149] opened 2017-09-15 20:53 UTC
Despite the comment in example/frontends/openid_connect_frontend.yaml.example:

  db_uri: mongodb://db.example.com # optional: only support MongoDB, will default to in-memory storage if not specified

SATOSA won't load the oidc frontend w/o db_uri containing a mongodb URI

**Comment by jkakavas** [comment] 2017-09-16 12:36
I can verify this is *not* the case. We have been using the OIDC frontend in production for some time now with the in memory storage enabled. The db_uri parameter is not set in the config and the frontend is loaded successfully. 

In https://github.com/SUNET/SATOSA/blob/0b32298096452c528ea957f9e83dbb6afb78c2e2/src/satosa/frontends/openid_connect.py#L80

db_uri will be None since `.get()` returns `None` as the default value. No exception will be raised. I would encourage you to look at the exception that SATOSA raises and determine where the issue is. I will close this as invalid, but feel free to reopen this and prove me wrong with a stacktrace or open a new issue which correctly identifies your problem and we'll do our best to help out.

**Closed by jkakavas** 2017-09-16 12:36 UTC
Labels: invalid

**Comment by lhoekenga** [comment] 2017-09-17 03:14
SATOSA won't start If I comment out the db_uri /or/ leave it blank:

name: OIDC
config:
  signing_key_path: "/etc/pki/tls/private/signing.key"
  #db_uri: mongodb://db.example.com # optional: only support MongoDB, will default to in-memory storage if not specified
  provider:
    client_registration_supported: Yes
    response_types_supported: ["code", "id_token token"]
    subject_types_supported: ["pairwise"]
    scopes_supported: ["openid", "email"]

[2017-09-16 22:11:27] [ERROR]: Failed to create WSGI app.
Traceback (most recent call last):
  File "/opt/local/satosa/lib/python3.5/site-packages/satosa/proxy_server.py", line 148, in make_app
    return ToBytesMiddleware(WsgiApplication(satosa_config))
  File "/opt/local/satosa/lib/python3.5/site-packages/satosa/proxy_server.py", line 90, in __init__
    super().__init__(config)
  File "/opt/local/satosa/lib/python3.5/site-packages/satosa/base.py", line 68, in __init__
    self.request_micro_services + self.response_micro_services)
  File "/opt/local/satosa/lib/python3.5/site-packages/satosa/routing.py", line 59, in __init__
    for instance in frontends}
  File "/opt/local/satosa/lib/python3.5/site-packages/satosa/routing.py", line 59, in <dictcomp>
    for instance in frontends}
  File "/opt/local/satosa/lib/python3.5/site-packages/satosa/frontends/openid_connect.py", line 163, in register_endpoints
    self._create_provider(endpoint_baseurl)
  File "/opt/local/satosa/lib/python3.5/site-packages/satosa/frontends/openid_connect.py", line 83, in _create_provider
    self.provider = Provider(self.signing_key, capabilities, authz_state, cdb, Userinfo(self.user_db))
  File "/opt/local/satosa/lib/python3.5/site-packages/pyop/provider.py", line 71, in __init__
    self.configuration_information.verify()
  File "/opt/local/satosa/lib/python3.5/site-packages/oic/oic/message.py", line 877, in verify
    raise MissingRequiredAttribute("token_endpoint")
oic.oauth2.message.MissingRequiredAttribute: Missing required attribute 'token_endpoint'

**Comment by lhoekenga** [comment] 2017-09-18 20:03
It appears to be an incompatibility with oic 0.11.0.1
If use pip to uninstall SATOSA, and then reinstall it, "oic" reverts to v0.9.0.0, and the token_endpoint issue seems to go away

**Comment by jkakavas** [comment] 2017-09-19 07:48
Thanks for reporting this. SATOSA uses [pyOP](https://github.com/SUNET/pyop) for the openid connect frontend implementation and we have already seen that pyOP can't use pyoidc > 0.9.0.0 . I have now created an [issue](https://github.com/SUNET/pyop/issues/18) so that this can be tracker in pyOP
